---
# ---------------------------------------------------------
# UFW CONFIGURATION (UBUNTU/DEBIAN)
# ---------------------------------------------------------
- name: Configure UFW - Allow SSH (Anti-Lockout)
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Configure UFW - Allow Rancher ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ rancher_http_port }}"
    - "{{ rancher_port }}"

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled
