---
# ---------------------------------------------------------
# NETWORK SECURITY (UFW)
# ---------------------------------------------------------
- name: Configure UFW - Allow SSH (Anti-Lockout)
  community.general.ufw:
    rule: allow
    name: OpenSSH
  when: ansible_distribution == 'Ubuntu'

- name: Configure UFW - Allow Rancher ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "{{ rancher_http_port }}"
    - "{{ rancher_port }}"
  when: ansible_distribution == 'Ubuntu'

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled
  when: ansible_distribution == 'Ubuntu'
