---
# ---------------------------------------------------------
# FIREWALL CONFIGURATION (UFW for Ubuntu/Debian only)
# ---------------------------------------------------------

- name: Configure UFW (Debian/Ubuntu)
  ansible.builtin.include_tasks: firewall-debian.yml
